### ISSUE TITLE
Some Pmag 1.0 files do not open

### ISSUE THREAD

**Issue by dpastorgalan** [Jollyfant/PMAG2#11] opened 2019-01-09 15:52 UTC
It says it cannot recognize the type of PCA (I guess forced or not) into the statistics portal. And therefore it ignores it.

Also once you do that, you cannot upload again and you have to refresh.

**Comment by Jollyfant** [comment] 2019-01-09 15:53
Can you send me a file?

**Comment by dpastorgalan** [comment] 2019-01-09 15:56
This, for example 


—
Daniel Pastor-Galán

www.danielpastorgalan.com
Skype: monomalvadodelarmario

**Comment by Jollyfant** [comment] 2019-01-09 15:58
If you reply to the email it won't take the attachment. Upload it here or write me an email directly.

**Comment by dpastorgalan** [comment] 2019-01-09 16:31
[BD01.dir.zip](https://github.com/Jollyfant/PMAG2/files/2741578/BD01.dir.zip)

**Comment by Jollyfant** [comment] 2019-01-09 21:30
Ok the problem is that the type of PCA in the file is `GC` and not `gc`. Meaning that it does not understand this is τ3. I will fix it tomorrow!

**Comment by Jollyfant** [comment] 2019-01-10 08:55
Fixed in 305b683e3fa02c58c27e384c8b375dfafe3a8e8b.

**Closed by Jollyfant** 2019-01-10 08:55 UTC
